name: 'Build and Release'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            name: 'macos-aarch64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            name: 'macos-x86_64'
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
            name: 'windows-x86_64'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'NamsoGen ${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

  create-universal-macos:
    needs: build
    runs-on: macos-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create universal macOS binary
        run: |
          echo "Creating universal macOS binary would require additional setup with lipo"
          echo "This is an advanced configuration for later"

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release Summary
        run: |
          echo "## NamsoGen Release ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "### Downloads" >> $GITHUB_STEP_SUMMARY
          echo "- **macOS (Apple Silicon)**: Download the .dmg file" >> $GITHUB_STEP_SUMMARY
          echo "- **macOS (Intel)**: Download the .dmg file" >> $GITHUB_STEP_SUMMARY
          echo "- **Windows**: Download the .msi file" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation Instructions" >> $GITHUB_STEP_SUMMARY
          echo "1. Download the appropriate file for your system" >> $GITHUB_STEP_SUMMARY
          echo "2. Follow the standard installation process for your platform" >> $GITHUB_STEP_SUMMARY
          echo "3. Launch NamsoGen and start generating test credit card numbers" >> $GITHUB_STEP_SUMMARY